export type { LucideIcon as AppIcon } from 'lucide-react';

export const ICON_SIZE = {
  toolbar: 16,
  menu: 14,
  rowChevron: 15,
  rowGlyph: 12,
  tiny: 10,
} as const;

export {
  ArrowLeft as BackIcon,
  ArrowRight as ForwardIcon,
  ArrowUp as SendIcon,
  ArchiveRestore as RestoreIcon,
  AlertTriangle as WarningIcon,
  ArrowDownAZ as SortDescIcon,
  ArrowUpAZ as SortAscIcon,
  Bold as BoldIcon,
  Brain as BrainIcon,
  Bug as DebugIcon,
  CalendarDays as CalendarIcon,
  Check as CheckIcon,
  Square as CheckboxIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Clock3 as RecentsIcon,
  Code2 as CodeIcon,
  Command as CommandIcon,
  Copy as CopyIcon,
  CopyPlus as DuplicateIcon,
  CornerDownRight as ReferenceIcon,
  ExternalLink as OpenIcon,
  FilePenLine as DescriptionIcon,
  FilePenLine as NodeEditToolIcon,
  FilePlus2 as NodeCreateToolIcon,
  FileText as FileTextIcon,
  Hash as HashIcon,
  Hash as SupertagIcon,
  Heading1 as HeadingIcon,
  Highlighter as HighlightIcon,
  Home as HomeIcon,
  Eye as ShowIcon,
  EyeOff as HideIcon,
  Italic as ItalicIcon,
  KeyRound as PasswordIcon,
  Library as LibraryIcon,
  Link as UrlIcon,
  ListFilter as FilterIcon,
  ListChecks as OptionsIcon,
  ListPlus as AddChildIcon,
  Loader2 as LoaderIcon,
  Mail as EmailIcon,
  MessageCirclePlus as NewConversationIcon,
  MoreHorizontal as MoreIcon,
  MoveDown as MoveDownIcon,
  MoveRight as MoveToIcon,
  MoveUp as MoveUpIcon,
  Palette as ColorIcon,
  PanelTopClose as HideToolbarIcon,
  PanelTopOpen as ShowToolbarIcon,
  Paperclip as AttachmentIcon,
  PanelLeftClose as SidebarCollapseIcon,
  PanelLeftOpen as SidebarExpandIcon,
  Pencil as PencilIcon,
  Pin as PinIcon,
  Plus as AddIcon,
  Redo2 as RedoIcon,
  RefreshCw as RefreshIcon,
  Rows3 as GroupIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Bot as AgentIcon,
  Sigma as FormulaIcon,
  Square as StopIcon,
  Strikethrough as StrikeIcon,
  TableProperties as FieldIcon,
  Table2 as TableIcon,
  Terminal as TerminalIcon,
  ToggleLeft as BooleanIcon,
  Trash2 as TrashIcon,
  Type as PlainTextIcon,
  Undo2 as UndoIcon,
  User as UserIcon,
  X as CloseIcon,
} from 'lucide-react';
