export type { LucideIcon as AppIcon } from 'lucide-react';

import { createElement } from 'react';
import { Square, type LucideIcon, type LucideProps } from 'lucide-react';

/**
 * Stop is a FILLED square. Lucide's `Square` is the very glyph this module also
 * exports as `CheckboxIcon`, so an unfilled stop control is drawn as an
 * unchecked checkbox — which is what the Subagent row's Stop looked like beside
 * its label. The composer filled the same glyph in its own CSS; stating it once
 * here means every Stop is a stop, wherever it is mounted. Callers may still
 * override `fill`, since the spread wins.
 */
export const StopIcon = ((props: LucideProps) => (
  createElement(Square, { fill: 'currentColor', ...props })
)) as unknown as LucideIcon;

export const ICON_SIZE = {
  toolbar: 16,
  menu: 14,
  rowChevron: 15,
  rowGlyph: 12,
  tiny: 10,
} as const;

export {
  ArrowLeft as BackIcon,
  ArrowRight as ForwardIcon,
  ArrowUp as SendIcon,
  ArchiveRestore as RestoreIcon,
  AlertTriangle as WarningIcon,
  ArrowDownAZ as SortDescIcon,
  ArrowUpAZ as SortAscIcon,
  Ban as BlockIcon,
  Bold as BoldIcon,
  Brain as BrainIcon,
  CalendarDays as CalendarIcon,
  CalendarClock as ScheduledIcon,
  Check as CheckIcon,
  CircleStop as BashStopToolIcon,
  Square as CheckboxIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Clock3 as RecentsIcon,
  Clock as ClockIcon,
  CircleHelp as QuestionToolIcon,
  Play as PlayIcon,
  Code2 as CodeIcon,
  Command as CommandIcon,
  Copy as CopyIcon,
  CopyPlus as DuplicateIcon,
  CornerDownRight as ReferenceIcon,
  ExternalLink as OpenIcon,
  MousePointerClick as ClickIcon,
  Database as DatabaseIcon,
  FileArchive as FileArchiveIcon,
  FileAudio as FileAudioIcon,
  FileCode2 as FileCodeIcon,
  FileX as FileDeleteToolIcon,
  FileImage as FileImageIcon,
  FilePenLine as DescriptionIcon,
  FilePenLine as FileEditToolIcon,
  FilePlus2 as FileWriteToolIcon,
  FileText as FileReadToolIcon,
  FileSpreadsheet as FileSpreadsheetIcon,
  FileText as FileTextIcon,
  FileVideo as FileVideoIcon,
  Folder as FolderIcon,
  FolderSearch as FileGlobToolIcon,
  GitBranchPlus as RunSpawnToolIcon,
  GitFork as GitForkIcon,
  Globe2 as WebSearchToolIcon,
  Hash as HashIcon,
  Hash as SupertagIcon,
  Heading1 as HeadingIcon,
  Highlighter as HighlightIcon,
  History as OutlineUndoStackToolIcon,
  Home as HomeIcon,
  Image as ImageIcon,
  Inbox as InboxIcon,
  Info as InfoIcon,
  Eye as ShowIcon,
  EyeOff as HideIcon,
  Italic as ItalicIcon,
  KeyRound as PasswordIcon,
  Languages as LanguagesIcon,
  Library as LibraryIcon,
  Link as UrlIcon,
  ListFilter as FilterIcon,
  List as ListIcon,
  ListChecks as OptionsIcon,
  // Distinct from OptionsIcon's ListChecks: a plan is a task list, and the two
  // co-occur in the agent panel.
  ListTodo as PlanToolIcon,
  ListPlus as AddChildIcon,
  ListPlus as NodeCreateToolIcon,
  ListTree as NodeReadToolIcon,
  ListX as NodeDeleteToolIcon,
  Loader2 as LoaderIcon,
  Maximize2 as ExpandIcon,
  Mail as EmailIcon,
  MoreHorizontal as MoreIcon,
  MoveDown as MoveDownIcon,
  MoveRight as MoveToIcon,
  MoveUp as MoveUpIcon,
  Palette as ColorIcon,
  Presentation as PresentationIcon,
  PanelTopClose as HideToolbarIcon,
  PanelTopOpen as ShowToolbarIcon,
  Paperclip as AttachmentIcon,
  PanelLeft as SidebarToggleIcon,
  PanelRight as AgentToggleIcon,
  Pencil as PencilIcon,
  Pin as PinIcon,
  Plus as AddIcon,
  Redo2 as RedoIcon,
  RefreshCw as RefreshIcon,
  Repeat as RepeatIcon,
  Rows3 as GroupIcon,
  CloudDownload as WebFetchToolIcon,
  Search as SearchIcon,
  SearchCode as FileGrepToolIcon,
  Settings as SettingsIcon,
  Bot as AgentIcon,
  GraduationCap as SkillIcon,
  Sigma as FormulaIcon,
  Sparkles as SkillAuthorToolIcon,
  SquarePen as NodeEditToolIcon,
  Strikethrough as StrikeIcon,
  TableProperties as FieldIcon,
  Table2 as TableIcon,
  Terminal as TerminalIcon,
  TextSearch as NodeSearchToolIcon,
  ToggleLeft as BooleanIcon,
  Trash2 as TrashIcon,
  Type as PlainTextIcon,
  Undo2 as UndoIcon,
  User as UserIcon,
  // An MCP server tool is a *connected* external tool, not an unidentified one.
  // Sharing Wrench with the unknown-tool fallback made a working integration and
  // an unmappable call render identically in the same transcript.
  Plug as McpToolIcon,
  Wrench as GenericToolIcon,
  X as CloseIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
} from 'lucide-react';
