export type { LucideIcon as AppIcon } from 'lucide-react';

export const ICON_SIZE = {
  toolbar: 16,
  menu: 14,
  rowChevron: 15,
  rowGlyph: 12,
  tiny: 10,
} as const;

export {
  ArrowLeft as BackIcon,
  ArrowRight as ForwardIcon,
  ArchiveRestore as RestoreIcon,
  AlertTriangle as WarningIcon,
  ArrowDownAZ as SortDescIcon,
  ArrowUpAZ as SortAscIcon,
  Bold as BoldIcon,
  CalendarDays as CalendarIcon,
  CheckSquare as CheckboxIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  Code2 as CodeIcon,
  CornerDownRight as ReferenceIcon,
  Hash as HashIcon,
  Highlighter as HighlightIcon,
  Home as HomeIcon,
  Eye as ShowIcon,
  EyeOff as HideIcon,
  Italic as ItalicIcon,
  KeyRound as PasswordIcon,
  Library as LibraryIcon,
  Link as UrlIcon,
  ListFilter as FilterIcon,
  ListChecks as OptionsIcon,
  ListPlus as AddChildIcon,
  Mail as EmailIcon,
  MoreHorizontal as MoreIcon,
  Palette as ColorIcon,
  Plus as AddIcon,
  Redo2 as RedoIcon,
  Rows3 as GroupIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Sigma as FormulaIcon,
  Strikethrough as StrikeIcon,
  Tag as TagIcon,
  ToggleLeft as BooleanIcon,
  Trash2 as TrashIcon,
  Type as PlainTextIcon,
  Undo2 as UndoIcon,
  User as UserIcon,
  X as CloseIcon,
} from 'lucide-react';
