import { describe, expect, test } from 'bun:test';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { OUTLINE_CAPABILITIES, OUTLINE_COMMAND_FAMILIES } from '../../src/outline/contract/capabilities';
import { renderOutlineCommandReference } from '../../src/outline/contract/commandReference';

const root = path.resolve(import.meta.dir, '..', '..');
const commandReference = path.join(
  root,
  'src',
  'main',
  'builtInSkills',
  'outline',
  'references',
  'commands.md',
);

describe('Outline Agent command reference', () => {
  test('is generated byte-for-byte from the executable capability registry', async () => {
    expect(await readFile(commandReference, 'utf8')).toBe(renderOutlineCommandReference());
  });

  test('gives the Agent one complete command and family inventory', async () => {
    const markdown = await readFile(commandReference, 'utf8');
    for (const capability of OUTLINE_CAPABILITIES) {
      expect(markdown).toContain(`| \`outline ${capability.name}\` |`);
    }
    for (const family of OUTLINE_COMMAND_FAMILIES.filter((entry) => !entry.name.includes(' '))) {
      expect(markdown).toContain(`| \`${family.name}\` | ${family.summary} |`);
    }
    expect(markdown).toContain('| Change multiple dependent resources | One ChangeSet');
    expect(markdown).toContain('| Import external data | `import inspect`, `import plan`');
  });
});
