export const DOCUMENT_COMMANDS = [
  'init_workspace',
  'get_projection',
  'search_nodes',
  'backlinks',
  'create_node',
  'create_rich_text_node',
  'create_tagged_node',
  'create_tag_and_tagged_node',
  'create_nodes_from_tree',
  'create_capture',
  'paste_nodes_into_node',
  'split_node',
  'apply_node_text_patch',
  'update_node_description',
  'set_node_checkbox_visible',
  'set_code_block',
  'set_code_language',
  'set_command_node',
  'set_command_schedule',
  'mark_command_fired',
  'create_image_node',
  'set_node_image',
  'set_view_toolbar_visible',
  'set_view_mode',
  'add_sort_rule',
  'update_sort_rule',
  'remove_sort_rule',
  'clear_sort_rules',
  'add_filter_rule',
  'update_filter_rule',
  'remove_filter_rule',
  'clear_filter_rules',
  'set_group_field',
  'add_display_field',
  'update_display_field',
  'remove_display_field',
  'set_node_icon',
  'set_node_banner',
  'merge_node_into',
  'move_node',
  'batch_move_nodes',
  'indent_node',
  'outdent_node',
  'trash_node',
  'batch_trash_nodes',
  'batch_indent_nodes',
  'batch_outdent_nodes',
  'batch_toggle_done',
  'batch_cycle_done_state',
  'batch_duplicate_nodes',
  'batch_move_nodes_up',
  'batch_move_nodes_down',
  'batch_apply_tag',
  'restore_node',
  'delete_node',
  'toggle_done',
  'cycle_done_state',
  'create_tag',
  'apply_tag',
  'remove_tag',
  'set_tag_config',
  'set_field_config',
  'create_field_def',
  'create_inline_field_after_node',
  'create_inline_field',
  'reuse_field_definition',
  'register_collected_option',
  'create_collected_field_option',
  'select_field_option',
  'add_field_reference',
  'set_field_free_text_value',
  'clear_field_value',
  'remove_field_value',
  'add_reference',
  'add_reference_conversion',
  'set_reference_target',
  'replace_node_with_reference',
  'replace_node_with_reference_conversion',
  'replace_node_with_inline_reference',
  'convert_reference_to_inline_node',
  'restore_inline_reference_node_to_reference',
  'ensure_date_node',
  'ensure_tag_search',
  'create_search_node',
  'set_search_node',
  'set_search_query_outline',
  'refresh_search_node_results',
  'undo',
  'redo',
] as const;

export const AGENT_COMMANDS = [
  'agent_restore_latest_conversation',
  'agent_restore_conversation',
  'agent_create_conversation',
  'agent_list_conversations',
  'agent_rename_conversation',
  'agent_delete_conversation',
  'agent_list_memory',
  'agent_update_memory',
  'agent_forget_memory',
  'agent_debug_snapshot',
  'agent_debug_history',
  'agent_debug_totals',
  'agent_debug_payload',
  'agent_payload_text',
  'agent_subagent_status',
  'agent_subagent_send',
  'agent_subagent_stop',
  'agent_send_message',
  'agent_run_command_now',
  'agent_edit_message',
  'agent_regenerate_message',
  'agent_retry_message',
  'agent_switch_branch',
  'agent_queue_follow_up',
  'agent_clear_follow_up',
  'agent_steer_conversation',
  'agent_clear_steer',
  'agent_resolve_approval',
  'agent_resolve_user_question',
  'agent_stop_conversation',
  'agent_reset_conversation',
  'agent_close_conversation',
  'agent_list_slash_commands',
  'agent_get_provider_settings',
  'agent_update_runtime_settings',
  'agent_get_tool_permission_settings',
  'agent_update_tool_permission_settings',
  'agent_upsert_provider_config',
  'agent_delete_provider_config',
  'agent_set_active_provider',
  'agent_set_provider_api_key',
  'agent_delete_provider_api_key',
  'agent_get_provider_secret_status',
  'agent_oauth_login',
  'agent_oauth_logout',
  'agent_oauth_respond',
  'agent_oauth_cancel',
  'agent_list_all_definitions',
  'agent_test_provider_connection',
  'agent_list_all_skills',
] as const;

export const ASSET_COMMANDS = [
  'ingest_asset',
  'lookup_asset',
  'delete_asset',
  'pick_image_files',
  'open_asset',
  'reveal_asset',
  'open_external_url',
] as const;

export type DocumentCommand = typeof DOCUMENT_COMMANDS[number];
export type AgentCommand = typeof AGENT_COMMANDS[number];
export type AssetCommand = typeof ASSET_COMMANDS[number];
export type LinCommand = DocumentCommand | AgentCommand | AssetCommand;

const documentCommands = new Set<string>(DOCUMENT_COMMANDS);
const agentCommands = new Set<string>(AGENT_COMMANDS);
const assetCommands = new Set<string>(ASSET_COMMANDS);

export function isDocumentCommand(command: string): command is DocumentCommand {
  return documentCommands.has(command);
}

export function isAgentCommand(command: string): command is AgentCommand {
  return agentCommands.has(command);
}

export function isAssetCommand(command: string): command is AssetCommand {
  return assetCommands.has(command);
}
