import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { DOMParser } from 'linkedom';
import { FILE_ICONS } from '../src/renderer/ui/editor/fileIcons';
import type { AppIcon } from '../src/renderer/ui/icons';

export const FILE_ICON_MASK_PATH = fileURLToPath(new URL('../src/renderer/styles/file-icon-masks.generated.css', import.meta.url));

export function fileIconMaskSvg(Icon: AppIcon): string {
  const document = new DOMParser().parseFromString(renderToStaticMarkup(createElement(Icon)), 'image/svg+xml');
  const svg = document.documentElement;
  // A mask image is a separate document; token sizes and inherited color cannot
  // cross that boundary. Keep geometry and native stroke values from the glyph.
  for (const node of [svg, ...svg.querySelectorAll('*')]) {
    for (const attribute of [...node.attributes]) {
      if (attribute.name === 'class' || attribute.name === 'focusable'
        || attribute.name.startsWith('aria-') || attribute.name.startsWith('data-')) {
        node.removeAttribute(attribute.name);
      } else if (attribute.value === 'currentColor') {
        node.setAttribute(attribute.name, 'black');
      }
    }
  }
  svg.removeAttribute('width');
  svg.removeAttribute('height');
  return svg.outerHTML;
}

export function generateFileIconMasks(): string {
  const rules = Object.entries(FILE_ICONS).map(([kind, Icon]) => {
    const image = `url("data:image/svg+xml,${encodeURIComponent(fileIconMaskSvg(Icon))}")`;
    return `.inline-ref-file-icon[data-file-icon-kind="${kind}"] {\n  -webkit-mask-image: ${image};\n  mask-image: ${image};\n}`;
  });
  return `/* Generated by bun scripts/generate-file-icon-masks.ts. Do not edit. */\n\n${rules.join('\n\n')}\n`;
}

if (import.meta.main) {
  const expected = generateFileIconMasks();
  if (process.argv.includes('--check')) {
    if (await readFile(FILE_ICON_MASK_PATH, 'utf8') !== expected) {
      throw new Error('File icon masks are stale. Run bun scripts/generate-file-icon-masks.ts');
    }
  } else {
    await writeFile(FILE_ICON_MASK_PATH, expected);
  }
}
