export const OUTLINE_PROTOCOL_VERSION = 1 as const;
export const OUTLINE_DESCRIPTOR_VERSION = 1 as const;
export const OUTLINE_STORAGE_VERSION = 2 as const;
export const OUTLINE_CLI_VERSION = '1.0.0' as const;
export const OUTLINE_APP_VERSION = '0.8.0' as const;
export const OUTLINE_PRIVATE_RUNTIME_CONTRACT_VERSION = 3 as const;

export const OUTLINE_DEFAULT_STARTUP_TIMEOUT_MS = 10_000;
export const OUTLINE_DEFAULT_COMMAND_TIMEOUT_MS = 60_000;
export const OUTLINE_MAX_COMMAND_TIMEOUT_MS = 300_000;
export const OUTLINE_DEFAULT_IDLE_TIMEOUT_MS = 5 * 60_000;
export const OUTLINE_EVENT_RETENTION = 10_000;
export const OUTLINE_RECOVERY_MINIMUM_DAYS = 30;
export const OUTLINE_RECOVERY_MINIMUM_OPERATIONS = 1_000;
export const OUTLINE_RECOVERY_BUDGET_BYTES = 2 * 1024 * 1024 * 1024;
export const OUTLINE_DIFF_INLINE_LIMIT_BYTES = 8 * 1024 * 1024;
